#!/bin/bash
# Deployment script for the full-stack todo app backend

echo "Backend deployment instructions:"
echo ""
echo "The backend (FastAPI application) needs to be deployed to a service that supports Python applications."
echo "Recommended platforms: Render, Railway, or AWS."
echo ""
echo "For Render deployment:"
echo "1. Go to https://render.com"
echo "2. Create a new Web Service"
echo "3. Connect to your GitHub repository"
echo "4. Set the runtime to Python"
echo "5. Set the build command to: pip install -r requirements.txt"
echo "6. Set the start command to: uvicorn src.main:app --host=0.0.0.0 --port=\$PORT"
echo "7. Add environment variables in the Render dashboard:"
echo "   - DATABASE_URL: PostgreSQL database URL"
echo "   - FRONTEND_URL: URL of your deployed frontend (e.g., https://your-app.vercel.app)"
echo "   - SECRET_KEY: Secret key for JWT tokens"
echo "   - ALGORITHM: Algorithm for JWT (default: HS256)"
echo "   - ACCESS_TOKEN_EXPIRE_MINUTES: Token expiration time (default: 30)"
echo ""
echo "For Railway deployment:"
echo "1. Go to https://railway.app"
echo "2. Create a new project"
echo "3. Connect to your GitHub repository"
echo "4. Select the backend directory"
echo "5. Add the same environment variables as mentioned above"
echo ""
echo "After deploying your backend, make note of the URL as you'll need it for the frontend deployment."