#!/bin/bash
# Main deployment script for the full-stack todo app

echo "==========================================="
echo "Full-Stack Todo App Deployment"
echo "==========================================="
echo ""
echo "This script will guide you through deploying the full-stack todo app."
echo ""
echo "The application consists of:"
echo "- Frontend: Next.js app (deployed to Vercel)"
echo "- Backend: FastAPI app (deployed to Render/Railway)"
echo ""

echo "Deployment Steps:"
echo "1. Deploy the backend first (API server)"
echo "2. Deploy the frontend (connects to the backend API)"
echo ""

echo "Before proceeding, please ensure:"
echo "- You have a Vercel account (for frontend)"
echo "- You have a Render or Railway account (for backend)"
echo "- You have your repository connected to these platforms"
echo ""

echo "Would you like to:"
echo "1. Deploy backend to Render"
echo "2. Deploy backend to Railway"
echo "3. View backend deployment instructions"
echo "4. Deploy frontend to Vercel"
echo "5. View full deployment guide"
echo ""
echo "Note: Deploy the backend first to get the API URL for the frontend."
echo ""

echo "To deploy manually:"
echo ""
echo "For Backend (choose one):"
echo "  Render: Use the deploy-backend.sh script or follow the README"
echo "  Railway: Use the deploy-backend.sh script or follow the README"
echo ""
echo "For Frontend:"
echo "  1. cd frontend"
echo "  2. vercel login"
echo "  3. vercel --prod"
echo "  4. Set NEXT_PUBLIC_API_URL environment variable to your backend URL"
echo ""