openapi: 3.0.0
info:
  title: Task API
  version: 1.0.0
  description: API for managing tasks with consistent UUID string IDs
servers:
  - url: http://localhost:8000
    description: Development server
  - url: https://api.todoapp.com
    description: Production server

paths:
  /api/{user_id}/tasks:
    get:
      summary: List tasks for a user
      parameters:
        - name: user_id
          in: path
          required: true
          description: UUID string of the user
          schema:
            type: string
            format: uuid
        - name: status
          in: query
          required: false
          description: Filter by task status
          schema:
            type: string
            enum: [pending, in-progress, completed, cancelled, on_hold]
        - name: priority
          in: query
          required: false
          description: Filter by task priority
          schema:
            type: string
            enum: [low, medium, high]
        - name: due_date_from
          in: query
          required: false
          description: Filter tasks with due date after this date
          schema:
            type: string
            format: date-time
        - name: due_date_to
          in: query
          required: false
          description: Filter tasks with due date before this date
          schema:
            type: string
            format: date-time
        - name: search
          in: query
          required: false
          description: Search term for title or description
          schema:
            type: string
        - name: completed
          in: query
          required: false
          description: Filter by completion status
          schema:
            type: boolean
        - name: skip
          in: query
          required: false
          description: Number of records to skip for pagination
          schema:
            type: integer
            default: 0
        - name: limit
          in: query
          required: false
          description: Maximum number of records to return
          schema:
            type: integer
            default: 100
            maximum: 1000
      responses:
        '200':
          description: List of tasks for the user
          content:
            application/json:
              schema:
                type: object
                properties:
                  tasks:
                    type: array
                    items:
                      $ref: '#/components/schemas/Task'
                  total:
                    type: integer
                    description: Total count of tasks matching filters
        '401':
          description: Unauthorized
        '403':
          description: Forbidden - user cannot access these tasks
        '404':
          description: User not found
      security:
        - BearerAuth: []

    post:
      summary: Create a new task for a user
      parameters:
        - name: user_id
          in: path
          required: true
          description: UUID string of the user
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskCreate'
      responses:
        '200':
          description: Task created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '400':
          description: Invalid input
        '401':
          description: Unauthorized
        '403':
          description: Forbidden - user cannot create tasks for this user
        '404':
          description: User not found
      security:
        - BearerAuth: []

  /api/{user_id}/tasks/{task_id}:
    get:
      summary: Get a specific task
      parameters:
        - name: user_id
          in: path
          required: true
          description: UUID string of the user
          schema:
            type: string
            format: uuid
        - name: task_id
          in: path
          required: true
          description: UUID string of the task
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Task details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden - user cannot access this task
        '404':
          description: Task not found
      security:
        - BearerAuth: []

    put:
      summary: Update a specific task
      parameters:
        - name: user_id
          in: path
          required: true
          description: UUID string of the user
          schema:
            type: string
            format: uuid
        - name: task_id
          in: path
          required: true
          description: UUID string of the task
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskUpdate'
      responses:
        '200':
          description: Task updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '400':
          description: Invalid input
        '401':
          description: Unauthorized
        '403':
          description: Forbidden - user cannot update this task
        '404':
          description: Task not found
      security:
        - BearerAuth: []

    delete:
      summary: Delete a specific task
      parameters:
        - name: user_id
          in: path
          required: true
          description: UUID string of the user
          schema:
            type: string
            format: uuid
        - name: task_id
          in: path
          required: true
          description: UUID string of the task
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Task deleted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '401':
          description: Unauthorized
        '403':
          description: Forbidden - user cannot delete this task
        '404':
          description: Task not found
      security:
        - BearerAuth: []

  /api/{user_id}/tasks/{task_id}/complete:
    patch:
      summary: Toggle task completion status
      parameters:
        - name: user_id
          in: path
          required: true
          description: UUID string of the user
          schema:
            type: string
            format: uuid
        - name: task_id
          in: path
          required: true
          description: UUID string of the task
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Task completion status updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden - user cannot update this task
        '404':
          description: Task not found
      security:
        - BearerAuth: []

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer

  schemas:
    Task:
      type: object
      required:
        - id
        - title
        - status
        - priority
        - user_id
        - created_at
        - updated_at
      properties:
        id:
          type: string
          format: uuid
          description: Unique identifier for the task
        title:
          type: string
          maxLength: 255
          description: Task title
        description:
          type: string
          description: Task description (optional)
        status:
          type: string
          enum: [pending, in-progress, completed, cancelled, on_hold]
          description: Current status of the task
        priority:
          type: string
          enum: [low, medium, high]
          description: Priority level of the task
        due_date:
          type: string
          format: date-time
          description: Due date for the task (optional)
        tags:
          type: string
          description: Comma-separated tags (optional)
        is_recurring:
          type: boolean
          description: Whether the task is recurring
        recurrence_pattern:
          type: object
          description: Recurrence pattern configuration (optional)
        user_id:
          type: string
          format: uuid
          description: ID of the user who owns this task
        created_at:
          type: string
          format: date-time
          description: Timestamp when task was created
        updated_at:
          type: string
          format: date-time
          description: Timestamp when task was last updated
        completed_at:
          type: string
          format: date-time
          description: Timestamp when task was completed (optional)

    TaskCreate:
      type: object
      required:
        - title
        - priority
      properties:
        title:
          type: string
          maxLength: 255
        description:
          type: string
        status:
          type: string
          enum: [pending, in-progress, completed, cancelled, on_hold]
          default: pending
        priority:
          type: string
          enum: [low, medium, high]
        due_date:
          type: string
          format: date-time
        tags:
          type: string
        is_recurring:
          type: boolean
          default: false
        recurrence_pattern:
          type: object

    TaskUpdate:
      type: object
      properties:
        title:
          type: string
          maxLength: 255
        description:
          type: string
        status:
          type: string
          enum: [pending, in-progress, completed, cancelled, on_hold]
        priority:
          type: string
          enum: [low, medium, high]
        due_date:
          type: string
          format: date-time
        tags:
          type: string
        is_recurring:
          type: boolean
        recurrence_pattern:
          type: object
        completed_at:
          type: string
          format: date-time